# Machine Learning with Python(Assaginment)

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from sklearn import datasets

In [4]:
iris= datasets.load_iris()

In [5]:
x=iris.data
y=iris.target

# Import KNeighborsClassifier

In [6]:
from sklearn.neighbors import KNeighborsClassifier

In [7]:
knn=KNeighborsClassifier(n_neighbors=1)

In [8]:
knn.fit(x,y)

KNeighborsClassifier(n_neighbors=1)

In [9]:
# KNN Prediction
knn.predict([[3,5,4,2]])

array([2])

In [10]:
##print('Predicted target name:',iris['target_names'][knn.predict([[3,5,4,2]])])Predicted target name:['virginica']

In [11]:
x_new= np.array([[3,5,4,2]])
print('x_new.shape:',x_new.shape)

x_new.shape: (1, 4)


In [12]:
mypredict=knn.predict(x_new)

In [13]:
print('Prediction:',mypredict)
print('Predicted target name:',iris['target_names'][mypredict])

Prediction: [2]
Predicted target name: ['virginica']


In [14]:
x_new=[[3,5,4,2],[5,4,3,2]]
knn.predict(x_new)

array([2, 1])

In [15]:
knn=KNeighborsClassifier(n_neighbors=3)

In [16]:
knn.fit(x,y)

KNeighborsClassifier(n_neighbors=3)

In [17]:
knn.predict(x_new)

array([1, 1])

# Import LogisticRegression

In [18]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x,y)
lr.predict(x_new)


C:\Users\Anushka Debnath\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0, 0])

In [19]:
from sklearn.datasets import load_iris
iris=load_iris()

In [20]:
x=iris.data
y=iris.target

In [21]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)

In [22]:
knn.fit(x,y)

KNeighborsClassifier()

In [23]:
knn.predict(x)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [24]:
knn.predict(x)[0:5]

array([0, 0, 0, 0, 0])

In [25]:
y_pred=knn.predict(x)
len(y_pred)

150

In [26]:
knn.score(x,y)

0.9666666666666667

# Import Accuracy_score

In [27]:
from sklearn.metrics import accuracy_score
import numpy as np
y_true=np.array([0,0,0,1,1,1,2,2,2,2])
y_pred1=np.array([0,0,0,1,1,1,2,2,2,2])
accuracy_score(y_true,y_pred1)

1.0

# Import Metrics

In [28]:
from sklearn import metrics
print(metrics.accuracy_score(y,y_pred))

0.9666666666666667


In [29]:
np.mean(y_pred==y)

0.9666666666666667

In [30]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=1)
knn.fit(x,y)
y_pred=knn.predict(x)
print(metrics.accuracy_score(y,y_pred))

1.0


In [31]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y,y_pred)

array([[50,  0,  0],
       [ 0, 50,  0],
       [ 0,  0, 50]], dtype=int64)