# Machine Learning with Python(Assaginment)

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from sklearn import datasets

In [4]:
iris= datasets.load_iris()

In [5]:
x=iris.data
y=iris.target

# Import KNeighborsClassifier

In [6]:
from sklearn.neighbors import KNeighborsClassifier

In [7]:
knn=KNeighborsClassifier(n_neighbors=1)

In [8]:
knn.fit(x,y)

KNeighborsClassifier(n_neighbors=1)

In [9]:
# KNN Prediction
knn.predict([[3,5,4,2]])

array([2])

In [10]:
##print('Predicted target name:',iris['target_names'][knn.predict([[3,5,4,2]])])Predicted target name:['virginica']

In [11]:
x_new= np.array([[3,5,4,2]])
print('x_new.shape:',x_new.shape)

x_new.shape: (1, 4)


In [12]:
mypredict=knn.predict(x_new)

In [13]:
print('Prediction:',mypredict)
print('Predicted target name:',iris['target_names'][mypredict])

Prediction: [2]
Predicted target name: ['virginica']


In [14]:
x_new=[[3,5,4,2],[5,4,3,2]]
knn.predict(x_new)

array([2, 1])

In [15]:
knn=KNeighborsClassifier(n_neighbors=3)

In [16]:
knn.fit(x,y)

KNeighborsClassifier(n_neighbors=3)

In [17]:
knn.predict(x_new)

array([1, 1])

# Import LogisticRegression

In [18]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x,y)
lr.predict(x_new)


C:\Users\Anushka Debnath\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0, 0])

In [19]:
from sklearn.datasets import load_iris
iris=load_iris()

In [20]:
x=iris.data
y=iris.target

In [21]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)

In [22]:
knn.fit(x,y)

KNeighborsClassifier()

In [23]:
knn.predict(x)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [24]:
knn.predict(x)[0:5]

array([0, 0, 0, 0, 0])

In [25]:
y_pred=knn.predict(x)
len(y_pred)

150

In [26]:
knn.score(x,y)

0.9666666666666667

# Import Accuracy_score

In [27]:
from sklearn.metrics import accuracy_score
import numpy as np
y_true=np.array([0,0,0,1,1,1,2,2,2,2])
y_pred1=np.array([0,0,0,1,1,1,2,2,2,2])
accuracy_score(y_true,y_pred1)

1.0

# Import Metrics

In [28]:
from sklearn import metrics
print(metrics.accuracy_score(y,y_pred))

0.9666666666666667


In [29]:
np.mean(y_pred==y)

0.9666666666666667

In [30]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=1)
knn.fit(x,y)
y_pred=knn.predict(x)
print(metrics.accuracy_score(y,y_pred))

1.0


In [31]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y,y_pred)

array([[50,  0,  0],
       [ 0, 50,  0],
       [ 0,  0, 50]], dtype=int64)

# Decision Tree Classifier

In [32]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier

iris = load_iris()

In [33]:
X = iris.data
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [34]:
X = iris.data[:, 3:]
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [35]:
X = iris.data[:, 2:]
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [36]:
y = iris.target
tree_clf = DecisionTreeClassifier(max_depth=2, random_state=42)
tree_clf.fit(X, y)

DecisionTreeClassifier(max_depth=2, random_state=42)

# Install Graphviz

In [37]:
#!pip install graphviz
from sklearn.tree import export_graphviz
from graphviz import Source
export_graphviz(
        tree_clf,
        out_file='tree.dot',
        feature_names=iris.feature_names[2:],
        class_names=iris.target_names,
        rounded=True,
        filled=True
    )

In [38]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
%matplotlib inline 
import matplotlib.pyplot as plt
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score

In [39]:
url='https://raw.githubusercontent.com/FazlyRabbiBD/Data-Science-Book/master/data-indian-liver-Patient.csv'
df = pd.read_csv(url)
df.head()

Age  Gender    TB   DB  AAP  SGPT  SGOT   TP  ALB   AGR  Status
0   65  Female   0.7  0.1  187    16    18  6.8  3.3  0.90       1
1   62    Male  10.9  5.5  699    64   100  7.5  3.2  0.74       1
2   62    Male   7.3  4.1  490    60    68  7.0  3.3  0.89       1
3   58    Male   1.0  0.4  182    14    20  6.8  3.4  1.00       1
4   72    Male   3.9  2.0  195    27    59  7.3  2.4  0.40       1

In [40]:
df.isnull().values.any()

True

In [41]:
null_columns=df.columns[df.isnull().any()]
print(df[df.isnull().any(axis=1)][null_columns].head())

     AGR
209  NaN
241  NaN
253  NaN
312  NaN


In [42]:
df.dropna(how='any', axis=0,inplace=True)

In [43]:
d = {'Female':1 , 'Male': 0}
df['Gender'] = df['Gender'].map(d)

In [44]:
X = df[['Age', 'Gender', 'TB', 'DB', 'AAP', 'SGPT', 'SGOT', 'TP', 'ALB', 'AGR']]
y = df['Status']

In [45]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (463, 10) (463,)
Test set: (116, 10) (116,)


# Import Support Vactor Machine

In [46]:
from sklearn import svm
clf = svm.SVC(kernel='rbf')
clf.fit(X_train,y_train) 

SVC()

#  First Prediction

In [47]:
pred=clf.predict(X_test)
print(classification_report(y_test, pred))
print('\nAccuracy: {0:.4f}'.format(accuracy_score(y_test, pred)))
print(confusion_matrix(y_test,pred))

              precision    recall  f1-score   support

           1       0.69      1.00      0.82        80
           2       0.00      0.00      0.00        36

    accuracy                           0.69       116
   macro avg       0.34      0.50      0.41       116
weighted avg       0.48      0.69      0.56       116


Accuracy: 0.6897
[[80  0]
 [36  0]]


C:\Users\Anushka Debnath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Anushka Debnath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Anushka Debnath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [48]:
from sklearn import svm
clfL = svm.SVC(kernel='linear')
clfL.fit(X_train, y_train) 

SVC(kernel='linear')

In [49]:
pred1=clfL.predict(X_test)
print(classification_report(y_test, pred1))
print('\nAccuracy: {0:.4f}'.format(accuracy_score(y_test, pred1)))
print(confusion_matrix(y_test,pred1))

              precision    recall  f1-score   support

           1       0.69      1.00      0.82        80
           2       0.00      0.00      0.00        36

    accuracy                           0.69       116
   macro avg       0.34      0.50      0.41       116
weighted avg       0.48      0.69      0.56       116


Accuracy: 0.6897
[[80  0]
 [36  0]]


C:\Users\Anushka Debnath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Anushka Debnath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Anushka Debnath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [51]:
clfP = svm.SVC(C=2.0, kernel='poly', degree=3)
clfP.fit(X_train, y_train)

SVC(C=2.0, kernel='poly')

# Prediction Number Second

In [52]:
pred2=clfP.predict(X_test)
print(classification_report(y_test, pred2))
print('\nAccuracy: {0:.4f}'.format(accuracy_score(y_test, pred2)))
print(confusion_matrix(y_test,pred2))

              precision    recall  f1-score   support

           1       0.69      1.00      0.82        80
           2       0.00      0.00      0.00        36

    accuracy                           0.69       116
   macro avg       0.34      0.50      0.41       116
weighted avg       0.48      0.69      0.56       116


Accuracy: 0.6897
[[80  0]
 [36  0]]


C:\Users\Anushka Debnath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Anushka Debnath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Anushka Debnath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
