# Numpy Function and Its Use

In [1]:
import numpy as np

In [2]:
#Array 
a=np.array([1,2,3])

In [3]:
b=np.array([(1.5,2,3),(4,5,6)],dtype=float)

In [4]:
c=np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]],dtype=float)

In [5]:
#Zeros 
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [6]:
#Ones 
np.ones((2,3,4),dtype=np.int32)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [7]:
d= np.arange(10,25,5)

In [8]:
d

array([10, 15, 20])

In [9]:
#Linspace 
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [10]:
e=np.full((2,2),7)

In [11]:
e

array([[7, 7],
       [7, 7]])

In [12]:
#Eye 
f=np.eye(2)

In [13]:
f

array([[1., 0.],
       [0., 1.]])

In [14]:
#Random Values
np.random.random((2,2))

array([[0.03878104, 0.45531765],
       [0.66398181, 0.43815961]])

In [15]:
#Empty
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.save('ay_array',a)

In [17]:
a

array([1, 2, 3])

In [18]:
a.shape

(3,)

In [19]:
len(a)

3

In [20]:
b.ndim

2

In [21]:
e.size

4

In [22]:
#Check Dtype
b.dtype.name

'float64'

In [23]:
#Change Data Type
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
g=a-b

In [25]:
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [26]:
#Subtract
np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [27]:
#Add
np.add(b,a)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [28]:
#Multiply
np.multiply(b,a)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [29]:
#Divition
np.divide(b,a)

array([[1.5, 1. , 1. ],
       [4. , 2.5, 2. ]])

In [30]:
np.exp(b)

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [31]:
#Square
np.square(b)

array([[ 2.25,  4.  ,  9.  ],
       [16.  , 25.  , 36.  ]])

In [32]:
np.alen(b)

2

In [33]:
np.all(b)

True

In [34]:
#Max
np.amax(b)

6.0

In [35]:
#Min
np.amin(b)

1.5

In [36]:
#Sin
np.sin(b)

array([[ 0.99749499,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [37]:
#Cos
np.cos(b)

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [38]:
#Log
np.log(b)

array([[0.40546511, 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [39]:
b>2

array([[False, False,  True],
       [ True,  True,  True]])

In [40]:
np.array_equal(a,b)

False

In [41]:
#Sum
a.sum()

6

In [42]:
b.max(axis=0)

array([4., 5., 6.])

In [43]:
#Cumsum
b.cumsum(axis=1)

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [44]:
#Correlation and Coefficient
np.corrcoef(a)

1.0

In [45]:
#Standard Diviation
np.std(b)

1.5920810978785667

In [46]:
h=a.view()

In [47]:
h

array([1, 2, 3])

In [48]:
#Copy
np.copy(a)

array([1, 2, 3])

In [49]:
c.sort(axis=0)

In [50]:
c

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

In [51]:
#Transpose
i=np.transpose(b)

In [52]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [53]:
i.T

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [54]:
#ravel
b.ravel()

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [55]:
#Reshape
g.reshape(3,2)

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

In [56]:
#Append
np.append(h,g)

array([ 1. ,  2. ,  3. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

In [57]:
# Vertical Array
np.vstack((a,b))

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [58]:
#Horizontal Array
np.hstack((e,f))

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])